language: java
jdk: openjdk8
before_install: gradle wrapper
before_script:
- cd cob_spec
- mvn package
- cd ..
script:
- cd cob_spec
- java -jar fitnesse.jar -c "HttpTestSuite.ResponseTestSuite.SimpleGet?test&format=text"
- java -jar fitnesse.jar -c "HttpTestSuite.ResponseTestSuite.FourOhFour?test&format=text"
